[workspace]
resolver = "2"
members = ["core", "tui"]

[workspace.package]
version = "1.0.0"
edition = "2024"
license = "MIT"
authors = ["nicknad"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"
doc_markdown = "allow"
trivially_copy_pass_by_ref = "allow"
wrong_self_convention = "allow"
